## 📝 Introduction

#### The insurance industry relies heavily on data-driven decision-making to identify potential customers and reduce financial risk. With increasing competition and a diverse customer base, insurance companies need effective tools to predict customer behavior and improve product adoption.

#### In this project, we leverage machine learning techniques to analyze an anonymized dataset containing customer-related features. The aim is to build a robust predictive model that can support the insurance marketing team in targeting the right customers, while also providing actionable insights to increase product sales.

### 📝 Problem Statement

#### Task 1: Develop a predictive model that helps the insurance marketing team identify which customers are most likely to buy the insurance product.

#### Task 2: Provide data-driven suggestions to the marketing team on strategies to improve customer engagement and increase insurance product purchases.

#### The dataset used for this project comes from an insurance competition, where risk varies significantly across customers. Understanding the influence of different (though anonymized) features can help predict the likelihood of customers purchasing insurance and, in turn, assist in strategic marketing planning.

#### Domain: Finance (Insurance Analytics)

### Step 1: Import necessary libraries

In [1]:
# Step 1: Import necessary librariesa
import pandas as pd
import numpy as np

## Step 2: Read Dataset

In [2]:
data = pd.read_csv("train.csv")

In [3]:
data.shape

(595212, 59)

#### The data contains 595212 rows and 59 columns

In [4]:
data

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,7,0,2,2,5,1,0,0,1,0,...,9,1,5,8,0,1,1,0,0,1
1,9,0,1,1,7,0,0,0,0,1,...,3,1,1,9,0,1,1,0,1,0
2,13,0,5,4,9,1,0,0,0,1,...,4,2,7,7,0,1,1,0,1,0
3,16,0,0,1,2,0,0,1,0,0,...,2,2,4,9,0,0,0,0,0,0
4,17,0,0,2,0,1,0,1,0,0,...,3,1,1,3,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595207,1488013,0,3,1,10,0,0,0,0,0,...,4,1,9,6,0,1,1,0,1,1
595208,1488016,0,5,1,3,0,0,0,0,0,...,4,1,3,8,1,0,1,0,1,1
595209,1488017,0,1,1,10,0,0,1,0,0,...,3,2,2,6,0,0,1,0,0,0
595210,1488021,0,5,2,3,1,0,0,0,1,...,4,1,4,2,0,1,1,1,0,0
595211,1488027,0,0,1,8,0,0,1,0,0,...,4,4,3,8,0,1,0,0,0,0

In [5]:
data.head(10)

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,7,0,2,2,5,1,0,0,1,0,...,9,1,5,8,0,1,1,0,0,1
1,9,0,1,1,7,0,0,0,0,1,...,3,1,1,9,0,1,1,0,1,0
2,13,0,5,4,9,1,0,0,0,1,...,4,2,7,7,0,1,1,0,1,0
3,16,0,0,1,2,0,0,1,0,0,...,2,2,4,9,0,0,0,0,0,0
4,17,0,0,2,0,1,0,1,0,0,...,3,1,1,3,0,0,0,1,1,0
5,19,0,5,1,4,0,0,0,0,0,...,4,2,0,9,0,1,0,1,1,1
6,20,0,2,1,3,1,0,0,1,0,...,3,0,0,10,0,1,0,0,1,0
7,22,0,5,1,4,0,0,1,0,0,...,7,1,3,6,1,0,1,0,1,0
8,26,0,5,1,3,1,0,0,0,1,...,4,2,1,5,0,1,0,0,0,1
9,28,1,1,1,2,0,0,0,1,0,...,3,5,0,6,0,1,0,0,1,0

In [6]:
data

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,7,0,2,2,5,1,0,0,1,0,...,9,1,5,8,0,1,1,0,0,1
1,9,0,1,1,7,0,0,0,0,1,...,3,1,1,9,0,1,1,0,1,0
2,13,0,5,4,9,1,0,0,0,1,...,4,2,7,7,0,1,1,0,1,0
3,16,0,0,1,2,0,0,1,0,0,...,2,2,4,9,0,0,0,0,0,0
4,17,0,0,2,0,1,0,1,0,0,...,3,1,1,3,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595207,1488013,0,3,1,10,0,0,0,0,0,...,4,1,9,6,0,1,1,0,1,1
595208,1488016,0,5,1,3,0,0,0,0,0,...,4,1,3,8,1,0,1,0,1,1
595209,1488017,0,1,1,10,0,0,1,0,0,...,3,2,2,6,0,0,1,0,0,0
595210,1488021,0,5,2,3,1,0,0,0,1,...,4,1,4,2,0,1,1,1,0,0
595211,1488027,0,0,1,8,0,0,1,0,0,...,4,4,3,8,0,1,0,0,0,0

In [7]:
data.drop('id',axis=1,inplace = True )

## Step 3: Check Data

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 595212 entries, 0 to 595211
Data columns (total 58 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   target          595212 non-null  int64
 1   ps_ind_01       595212 non-null  int64
 2   ps_ind_02_cat   595212 non-null  int64
 3   ps_ind_03       595212 non-null  int64
 4   ps_ind_04_cat   595212 non-null  int64
 5   ps_ind_05_cat   595212 non-null  int64
 6   ps_ind_06_bin   595212 non-null  int64
 7   ps_ind_07_bin   595212 non-null  int64
 8   ps_ind_08_bin   595212 non-null  int64
 9   ps_ind_09_bin   595212 non-null  int64
 10  ps_ind_10_bin   595212 non-null  int64
 11  ps_ind_11_bin   595212 non-null  int64
 12  ps_ind_12_bin   595212 non-null  int64
 13  ps_ind_13_bin   595212 non-null  int64
 14  ps_ind_14       595212 non-null  int64
 15  ps_ind_15       595212 non-null  int64
 16  ps_ind_16_bin   595212 non-null  int64
 17  ps_ind_17_bin   595212 non-null  int64
 18  ps_ind_18_bin   595212 non-null  int64
 19  ps_reg_01       595212 non-null  float64
 20  ps_reg_02       595212 non-null  float64
 21  ps_reg_03       595212 non-null  float64
 22  ps_car_01_cat   595212 non-null  int64
 23  ps_car_02_cat   595212 non-null  int64
 24  ps_car_03_cat   595212 non-null  int64
 25  ps_car_04_cat   595212 non-null  int64
 26  ps_car_05_cat   595212 non-null  int64
 27  ps_car_06_cat   595212 non-null  int64
 28  ps_car_07_cat   595212 non-null  int64
 29  ps_car_08_cat   595212 non-null  int64
 30  ps_car_09_cat   595212 non-null  int64
 31  ps_car_10_cat   595212 non-null  int64
 32  ps_car_11_cat   595212 non-null  int64
 33  ps_car_11       595212 non-null  int64
 34  ps_car_12       595212 non-null  float64
 35  ps_car_13       595212 non-null  float64
 36  ps_car_14       595212 non-null  float64
 37  ps_car_15       595212 non-null  float64
 38  ps_calc_01      595212 non-null  float64
 39  ps_calc_02      595212 non-null  float64
 40  ps_calc_03      595212 non-null  float64
 41  ps_calc_04      595212 non-null  int64
 42  ps_calc_05      595212 non-null  int64
 43  ps_calc_06      595212 non-null  int64
 44  ps_calc_07      595212 non-null  int64
 45  ps_calc_08      595212 non-null  int64
 46  ps_calc_09      595212 non-null  int64
 47  ps_calc_10      595212 non-null  int64
 48  ps_calc_11      595212 non-null  int64
 49  ps_calc_12      595212 non-null  int64
 50  ps_calc_13      595212 non-null  int64
 51  ps_calc_14      595212 non-null  int64
 52  ps_calc_15_bin  595212 non-null  int64
 53  ps_calc_16_bin  595212 non-null  int64
 54  ps_calc_17_bin  595212 non-null  int64
 55  ps_calc_18_bin  595212 non-null  int64
 56  ps_calc_19_bin  595212 non-null  int64
 57  ps_calc_20_bin  595212 non-null  int64
dtypes: float64(10), int64(48)
memory usage: 263.4 MB

In [9]:
data.isnull().sum()

target            0
ps_ind_01         0
ps_ind_02_cat     0
ps_ind_03         0
ps_ind_04_cat     0
ps_ind_05_cat     0
ps_ind_06_bin     0
ps_ind_07_bin     0
ps_ind_08_bin     0
ps_ind_09_bin     0
ps_ind_10_bin     0
ps_ind_11_bin     0
ps_ind_12_bin     0
ps_ind_13_bin     0
ps_ind_14         0
ps_ind_15         0
ps_ind_16_bin     0
ps_ind_17_bin     0
ps_ind_18_bin     0
ps_reg_01         0
ps_reg_02         0
ps_reg_03         0
ps_car_01_cat     0
ps_car_02_cat     0
ps_car_03_cat     0
ps_car_04_cat     0
ps_car_05_cat     0
ps_car_06_cat     0
ps_car_07_cat     0
ps_car_08_cat     0
ps_car_09_cat     0
ps_car_10_cat     0
ps_car_11_cat     0
ps_car_11         0
ps_car_12         0
ps_car_13         0
ps_car_14         0
ps_car_15         0
ps_calc_01        0
ps_calc_02        0
ps_calc_03        0
ps_calc_04        0
ps_calc_05        0
ps_calc_06        0
ps_calc_07        0
ps_calc_08        0
ps_calc_09        0
ps_calc_10        0
ps_calc_11        0
ps_calc_12        0
ps_calc_13        0
ps_calc_14        0
ps_calc_15_bin    0
ps_calc_16_bin    0
ps_calc_17_bin    0
ps_calc_18_bin    0
ps_calc_19_bin    0
ps_calc_20_bin    0
dtype: int64

#### There is no null value

In [10]:
data.describe()

,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
count,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,...,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000
mean,0.036448,1.900378,1.358943,4.423318,0.416794,0.405188,0.393742,0.257033,0.163921,0.185304,...,5.441382,1.441918,2.872288,7.539026,0.122427,0.627840,0.554182,0.287182,0.349024,0.153318
std,0.187401,1.983789,0.664594,2.699902,0.493311,1.350642,0.488579,0.436998,0.370205,0.388544,...,2.332871,1.202963,1.694887,2.746652,0.327779,0.483381,0.497056,0.452447,0.476662,0.360295
min,0.000000,0.000000,-1.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,1.000000,2.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.000000,1.000000,3.000000,7.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,0.000000,3.000000,2.000000,6.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,...,7.000000,2.000000,4.000000,9.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000
max,1.000000,7.000000,4.000000,11.000000,1.000000,6.000000,1.000000,1.000000,1.000000,1.000000,...,19.000000,10.000000,13.000000,23.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [11]:
print(data['target'].value_counts(normalize=True))

target
0    0.963552
1    0.036448
Name: proportion, dtype: float64

## Step 4 Data Cleaning

#### •	Handle missing values
#### •	Remove duplicates 
#### •	Convert DataType
#### •	Encode categorical variables (LabelEncoder, OneHotEncoder)                                                                   
#### •   Handle outliers

In [12]:
data.isnull().mean() * 100  # Percent missing

target            0.0
ps_ind_01         0.0
ps_ind_02_cat     0.0
ps_ind_03         0.0
ps_ind_04_cat     0.0
ps_ind_05_cat     0.0
ps_ind_06_bin     0.0
ps_ind_07_bin     0.0
ps_ind_08_bin     0.0
ps_ind_09_bin     0.0
ps_ind_10_bin     0.0
ps_ind_11_bin     0.0
ps_ind_12_bin     0.0
ps_ind_13_bin     0.0
ps_ind_14         0.0
ps_ind_15         0.0
ps_ind_16_bin     0.0
ps_ind_17_bin     0.0
ps_ind_18_bin     0.0
ps_reg_01         0.0
ps_reg_02         0.0
ps_reg_03         0.0
ps_car_01_cat     0.0
ps_car_02_cat     0.0
ps_car_03_cat     0.0
ps_car_04_cat     0.0
ps_car_05_cat     0.0
ps_car_06_cat     0.0
ps_car_07_cat     0.0
ps_car_08_cat     0.0
ps_car_09_cat     0.0
ps_car_10_cat     0.0
ps_car_11_cat     0.0
ps_car_11         0.0
ps_car_12         0.0
ps_car_13         0.0
ps_car_14         0.0
ps_car_15         0.0
ps_calc_01        0.0
ps_calc_02        0.0
ps_calc_03        0.0
ps_calc_04        0.0
ps_calc_05        0.0
ps_calc_06        0.0
ps_calc_07        0.0
ps_calc_08        0.0
ps_calc_09        0.0
ps_calc_10        0.0
ps_calc_11        0.0
ps_calc_12        0.0
ps_calc_13        0.0
ps_calc_14        0.0
ps_calc_15_bin    0.0
ps_calc_16_bin    0.0
ps_calc_17_bin    0.0
ps_calc_18_bin    0.0
ps_calc_19_bin    0.0
ps_calc_20_bin    0.0
dtype: float64

### Remove duplicates

In [13]:
print("Before removing duplicates:", data.shape)
data.drop_duplicates(inplace=True)
print("After removing duplicates:", data.shape)

Before removing duplicates: (595212, 58)
After removing duplicates: (595212, 58)

#### There are no duplicates

### Convert DataType

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 595212 entries, 0 to 595211
Data columns (total 58 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   target          595212 non-null  int64
 1   ps_ind_01       595212 non-null  int64
 2   ps_ind_02_cat   595212 non-null  int64
 3   ps_ind_03       595212 non-null  int64
 4   ps_ind_04_cat   595212 non-null  int64
 5   ps_ind_05_cat   595212 non-null  int64
 6   ps_ind_06_bin   595212 non-null  int64
 7   ps_ind_07_bin   595212 non-null  int64
 8   ps_ind_08_bin   595212 non-null  int64
 9   ps_ind_09_bin   595212 non-null  int64
 10  ps_ind_10_bin   595212 non-null  int64
 11  ps_ind_11_bin   595212 non-null  int64
 12  ps_ind_12_bin   595212 non-null  int64
 13  ps_ind_13_bin   595212 non-null  int64
 14  ps_ind_14       595212 non-null  int64
 15  ps_ind_15       595212 non-null  int64
 16  ps_ind_16_bin   595212 non-null  int64
 17  ps_ind_17_bin   595212 non-null  int64
 18  ps_ind_18_bin   595212 non-null  int64
 19  ps_reg_01       595212 non-null  float64
 20  ps_reg_02       595212 non-null  float64
 21  ps_reg_03       595212 non-null  float64
 22  ps_car_01_cat   595212 non-null  int64
 23  ps_car_02_cat   595212 non-null  int64
 24  ps_car_03_cat   595212 non-null  int64
 25  ps_car_04_cat   595212 non-null  int64
 26  ps_car_05_cat   595212 non-null  int64
 27  ps_car_06_cat   595212 non-null  int64
 28  ps_car_07_cat   595212 non-null  int64
 29  ps_car_08_cat   595212 non-null  int64
 30  ps_car_09_cat   595212 non-null  int64
 31  ps_car_10_cat   595212 non-null  int64
 32  ps_car_11_cat   595212 non-null  int64
 33  ps_car_11       595212 non-null  int64
 34  ps_car_12       595212 non-null  float64
 35  ps_car_13       595212 non-null  float64
 36  ps_car_14       595212 non-null  float64
 37  ps_car_15       595212 non-null  float64
 38  ps_calc_01      595212 non-null  float64
 39  ps_calc_02      595212 non-null  float64
 40  ps_calc_03      595212 non-null  float64
 41  ps_calc_04      595212 non-null  int64
 42  ps_calc_05      595212 non-null  int64
 43  ps_calc_06      595212 non-null  int64
 44  ps_calc_07      595212 non-null  int64
 45  ps_calc_08      595212 non-null  int64
 46  ps_calc_09      595212 non-null  int64
 47  ps_calc_10      595212 non-null  int64
 48  ps_calc_11      595212 non-null  int64
 49  ps_calc_12      595212 non-null  int64
 50  ps_calc_13      595212 non-null  int64
 51  ps_calc_14      595212 non-null  int64
 52  ps_calc_15_bin  595212 non-null  int64
 53  ps_calc_16_bin  595212 non-null  int64
 54  ps_calc_17_bin  595212 non-null  int64
 55  ps_calc_18_bin  595212 non-null  int64
 56  ps_calc_19_bin  595212 non-null  int64
 57  ps_calc_20_bin  595212 non-null  int64
dtypes: float64(10), int64(48)
memory usage: 263.4 MB

### Convert DataType

#### By default, pandas loads numbers as int64 or float64, which are heavy.

#### Example:
#### int64 → 8 bytes
#### int8 → 1 byte

#### If a column only has values 0/1 (binary), storing it as int64 wastes 7 extra bytes per row.
####  Converting reduces RAM usage & speeds up processing.

In [15]:
print(data["ps_ind_06_bin"].unique())

[0 1]

#### 1) Binary (*_bin)
#### Values: 0/1 → can safely use int8.

#### 2) Categorical (*_cat)
#### These are labels, not numbers → use category (pandas) or encode later for ML.

#### 3) Numeric (continuous)
#### Columns like ps_reg_01, ps_car_13, ps_calc_01 etc.
#### Keep as float32 (lighter than float64, but still precise enough).

#### 4) ID / Target
#### id → usually drop (not predictive).
#### target → keep as int8 (0/1).

In [16]:
cat_cols = [c for c in data.columns if "_cat" in c]
bin_cols = [c for c in data.columns if "_bin" in c]
num_cols = [c for c in data.columns if c not in (cat_cols + bin_cols + ["id","target"])]

data[cat_cols] = data[cat_cols].astype("category")
data[bin_cols] = data[bin_cols].astype("int8")
data[num_cols] = data[num_cols].astype("float32")
data["target"] = data["target"].astype("int8")

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 595212 entries, 0 to 595211
Data columns (total 58 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   target          595212 non-null  int8
 1   ps_ind_01       595212 non-null  float32
 2   ps_ind_02_cat   595212 non-null  category
 3   ps_ind_03       595212 non-null  float32
 4   ps_ind_04_cat   595212 non-null  category
 5   ps_ind_05_cat   595212 non-null  category
 6   ps_ind_06_bin   595212 non-null  int8
 7   ps_ind_07_bin   595212 non-null  int8
 8   ps_ind_08_bin   595212 non-null  int8
 9   ps_ind_09_bin   595212 non-null  int8
 10  ps_ind_10_bin   595212 non-null  int8
 11  ps_ind_11_bin   595212 non-null  int8
 12  ps_ind_12_bin   595212 non-null  int8
 13  ps_ind_13_bin   595212 non-null  int8
 14  ps_ind_14       595212 non-null  float32
 15  ps_ind_15       595212 non-null  float32
 16  ps_ind_16_bin   595212 non-null  int8
 17  ps_ind_17_bin   595212 non-null  int8
 18  ps_ind_18_bin   595212 non-null  int8
 19  ps_reg_01       595212 non-null  float32
 20  ps_reg_02       595212 non-null  float32
 21  ps_reg_03       595212 non-null  float32
 22  ps_car_01_cat   595212 non-null  category
 23  ps_car_02_cat   595212 non-null  category
 24  ps_car_03_cat   595212 non-null  category
 25  ps_car_04_cat   595212 non-null  category
 26  ps_car_05_cat   595212 non-null  category
 27  ps_car_06_cat   595212 non-null  category
 28  ps_car_07_cat   595212 non-null  category
 29  ps_car_08_cat   595212 non-null  category
 30  ps_car_09_cat   595212 non-null  category
 31  ps_car_10_cat   595212 non-null  category
 32  ps_car_11_cat   595212 non-null  category
 33  ps_car_11       595212 non-null  float32
 34  ps_car_12       595212 non-null  float32
 35  ps_car_13       595212 non-null  float32
 36  ps_car_14       595212 non-null  float32
 37  ps_car_15       595212 non-null  float32
 38  ps_calc_01      595212 non-null  float32
 39  ps_calc_02      595212 non-null  float32
 40  ps_calc_03      595212 non-null  float32
 41  ps_calc_04      595212 non-null  float32
 42  ps_calc_05      595212 non-null  float32
 43  ps_calc_06      595212 non-null  float32
 44  ps_calc_07      595212 non-null  float32
 45  ps_calc_08      595212 non-null  float32
 46  ps_calc_09      595212 non-null  float32
 47  ps_calc_10      595212 non-null  float32
 48  ps_calc_11      595212 non-null  float32
 49  ps_calc_12      595212 non-null  float32
 50  ps_calc_13      595212 non-null  float32
 51  ps_calc_14      595212 non-null  float32
 52  ps_calc_15_bin  595212 non-null  int8
 53  ps_calc_16_bin  595212 non-null  int8
 54  ps_calc_17_bin  595212 non-null  int8
 55  ps_calc_18_bin  595212 non-null  int8
 56  ps_calc_19_bin  595212 non-null  int8
 57  ps_calc_20_bin  595212 non-null  int8
dtypes: category(14), float32(26), int8(18)
memory usage: 77.2 MB

###	Encode categorical variables

#### The Data is already encoded

## Handling Outliers

### View Outliers

In [19]:
import pandas as pd

# Simple outlier check using IQR
num_cols = data.select_dtypes(include=["int64","float64","float32"]).columns
outlier_counts = {}

for col in num_cols:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = ((data[col] < lower) | (data[col] > upper)).sum()
    if outliers > 0:
        outlier_counts[col] = outliers

# Show columns with outliers, sorted
outlier_counts = pd.Series(outlier_counts).sort_values(ascending=False)
print(outlier_counts)

ps_reg_03     120865
ps_car_14      58905
ps_calc_04     38105
ps_reg_02      36793
ps_calc_12     35259
ps_car_15      27409
ps_car_13      26913
ps_car_11      25988
ps_calc_14     16086
ps_car_12      15356
ps_ind_14       6380
ps_calc_11      6080
ps_calc_13      5505
ps_calc_10      3642
ps_calc_06      1338
ps_calc_08       942
ps_calc_07       570
ps_calc_09       263
dtype: int64

### Handle Outliers

In [31]:
for col in data.select_dtypes(include=["int64","float64"]).columns:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    data[col] = data[col].clip(lower, upper)

### Repalcing -1 with NAN

#### We replace -1 with NaN because -1 is just a placeholder for “missing”, while NaN is the proper way to represent missing values in ML workflows. This prevents the model from misinterpreting -1 as a real numeric value.

In [22]:
import numpy as np

# Replace -1 with NaN
data = data.replace(-1, np.nan)

# Fill NaN with median (better than mean for skewed data)
data = data.fillna(data.median(numeric_only=True))

C:\Users\Admin\AppData\Local\Temp\ipykernel_1800\1889487372.py:4: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  data = data.replace(-1, np.nan)

In [23]:
# Numeric imputation
num_cols = data.select_dtypes(include=["int64","float64"]).columns
data[num_cols] = data[num_cols].apply(lambda x: x.fillna(x.median()))

# Categorical imputation
cat_cols = [col for col in data.columns if "_cat" in col or "_bin" in col]
for col in cat_cols:
    data[col] = data[col].fillna(data[col].mode()[0])

## Model Creation

### Defining X & Y

In [24]:
X = data.drop(columns = ['target'])
y = data['target']

### Train - Test Split

In [25]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y, test_size = 0.2, stratify=y, random_state=42)
print(X_train.shape, X_test.shape)

(476169, 57) (119043, 57)

### Using Smote

In [26]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

print("Before SMOTE:", y_train.value_counts())
print("After SMOTE:", y_train_res.value_counts())

Before SMOTE: target
0    458814
1     17355
Name: count, dtype: int64
After SMOTE: target
0    458814
1    458814
Name: count, dtype: int64

## Model Training

### Random Forest

In [27]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

# 1. Initialize Random Forest
rf = RandomForestClassifier(
    n_estimators=200,      # number of trees
    max_depth=None,        # let trees grow fully (can tune later)
    random_state=42,
    n_jobs=-1,             # use all CPU cores
    class_weight="balanced"      # not needed since we used SMOTE
)

# 2. Train on SMOTE-resampled training data
rf.fit(X_train_res, y_train_res)

# 3. Predictions on test set
y_pred = rf.predict(X_test)
y_proba = rf.predict_proba(X_test)[:, 1]  # probabilities for ROC-AUC

# 4. Evaluation
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nROC-AUC Score:", roc_auc_score(y_test, y_proba))

Confusion Matrix:
 [[114704      0]
 [  4339      0]]

C:\Users\Admin\.conda\envs\Tanmay\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Admin\.conda\envs\Tanmay\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Admin\.conda\envs\Tanmay\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Classification Report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98    114704
           1       0.00      0.00      0.00      4339

    accuracy                           0.96    119043
   macro avg       0.48      0.50      0.49    119043
weighted avg       0.93      0.96      0.95    119043


ROC-AUC Score: 0.5944157686623585

#### Class 0 (majority) → almost perfect (recall = 1.00, precision = 0.96).

#### Class 1 (minority, the one we care about) → completely ignored (precision = 0.00, recall = 0.00, F1 = 0.00).

#### ROC-AUC ≈ 0.59 → barely better than random guessing (0.5).

#### 👉 Even though overall accuracy looks high (96%), the model is useless for detecting class 1.

In [29]:
# Convert categorical columns to int
cat_cols = [col for col in X_train.columns if "_cat" in col]
X_train[cat_cols] = X_train[cat_cols].astype("int")
X_test[cat_cols] = X_test[cat_cols].astype("int")

### Xgboost

In [30]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

# Compute class weight ratio
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
print("Scale_pos_weight:", scale_pos_weight)

# Initialize XGBoost
xgb = XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,  # <-- handle imbalance
    random_state=42,
    n_jobs=-1,
    eval_metric="auc"
)

# Train
xgb.fit(X_train, y_train)

# Predictions
y_pred = xgb.predict(X_test)
y_proba = xgb.predict_proba(X_test)[:, 1]

# Evaluation
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nROC-AUC Score:", roc_auc_score(y_test, y_proba))

Scale_pos_weight: 26.436992221261885
Confusion Matrix:
 [[83206 31498]
 [ 2423  1916]]

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.73      0.83    114704
           1       0.06      0.44      0.10      4339

    accuracy                           0.72    119043
   macro avg       0.51      0.58      0.47    119043
weighted avg       0.94      0.72      0.80    119043


ROC-AUC Score: 0.6222831922487962

#### 📈 Classification Report

#### Class 0 (majority)

#### Precision = 0.97 → when it predicts 0, it’s correct most of the time.

#### Recall = 0.73 → it misses ~27% of actual 0s.

#### Class 1 (minority, the important one)

#### Precision = 0.06 → only 6% of predicted 1s are actually correct → many false positives.

#### Recall = 0.44 → model finds 44% of real positives, which is much better than before (Random Forest had 0.00 recall).

#### Macro avg F1 = 0.47 → overall balance between the two classes is still low.

## Conclusion

#### The results demonstrate that XGBoost outperforms Random Forest when dealing with imbalanced data, particularly in capturing the minority class. While Random Forest completely failed to identify class 1, XGBoost achieved a recall of 44% for the minority class, albeit with low precision. This trade-off highlights the importance of threshold tuning in imbalanced classification problems.

#### However, due to the anonymized nature of the dataset, we cannot interpret which features are most influential or provide business-level insights. Future improvements would require feature documentation to connect model outputs with real-world meaning.

#### Overall, this project shows that robust preprocessing, imbalance handling, and careful model selection can significantly improve performance on challenging, imbalanced datasets — even when interpretability is limited.

In [ ]:
Challenges & Techniques

1️⃣ Missing Values

Some columns may have gaps.

→ Checked missing % and saved a table to decide on drop/impute later.

2️⃣ Data Types

All columns were numeric, but some (*_cat) are coded categories.

→ Suggest converting them to category for proper summaries & encoding.

3️⃣ Large Size

100k rows × 59 cols slowed plots.

→ Used a 1k-row sample for quick visuals.

4️⃣ Target Identification

Label not explicit; found target as likely output.

→ Confirm before modeling.

5️⃣ Scaling & Outliers

Wide ranges & skewed values.

→ Used histograms/boxplots; plan scaling or log-transform if needed.

6️⃣ Correlations

Many features may overlap.

→ Checked a heatmap for multicollinearity.

7️⃣ Imbalance Risk

Binary targets often skewed.

→ Checked target counts; use SMOTE or class weights if imbalanced.